/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
static yyconst short int yy_acclist[411] =
    {   0,
       71,   69,   70,   59,   69,   70,   59,   70,   52,   69,
       70,   69,   70,   56,   69,   70,   53,   69,   70,   52,
       69,   70,   69,   70,   51,   69,   70,   52,   69,   70,
       52,   69,   70,   56,   69,   70,   52,   69,   70,   51,
       69,   70,   53,   69,   70,   42,   69,   70,   43,   69,
       70,   54,   69,   70,   50,   54,   69,   70,   53,   69,
       70,   55,   69,   70,   53,   69,   70,   54,   69,   70,
       58,   69,   70,   58,   69,   70,   69,   70,   53,   69,
       70,   58,   69,   70,   58,   69,   70,   58,   69,   70,
       58,   69,   70,   58,   69,   70,   58,   69,   70,   58,

       69,   70,   58,   69,   70,   58,   69,   70,   58,   69,
       70,   58,   69,   70,   58,   69,   70,   58,   69,   70,
       58,   69,   70,   58,   69,   70,   58,   69,   70,   50,
       51,   69,   70,   53,   69,   70,   52,   69,   70,   56,
       69,   70,    3,   70,    3,   70,    3,   70,   67,   68,
       70,   68,   70,   59,   53,   49,   56,   57,   55,   57,
       52,   51,   45,    1,   45,   42,   42,   42,   42,   43,
       43,   43,   43,   50,   53,   53,   58,   60,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   33,   58,   58,
       58,   58,   58,   58,   58,   37,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,    3,    3,
        2,   67,   48,   54,   45,    4,   46,   42,   42,   42,
       42,   44,   43,   43,   43,   43,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       35,   58,   58,   58,   16,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   61,   45,   46,   42,   44,   44,   44,   43,
       58,   58,   58,    8,   58,   58,   30,   58,    9,   58,
       58,   58,   58,   58,   34,   58,   12,   58,   58,   58,
       36,   58,   58,   17,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   27,   58,   58,
       58,   44,   44,   47,   44,   44,    5,   58,   58,   58,
       29,   58,   10,   58,   58,   58,   58,   58,   14,   58,
       58,   58,   58,   58,   20,   58,   58,   58,   58,   58,
       58,   58,   25,   58,   58,   58,   41,   58,   62,   65,
       47,   44,   58,   58,   58,   58,   58,   11,   58,   13,
       58,   15,   58,   58,   58,   38,   58,   21,   58,   39,
       58,   22,   58,   23,   58,   40,   58,   58,   58,   58,
       63,   58,   58,   58,   32,   58,   58,   58,   24,   58,
       58,   58,   64,    6,   58,   58,   31,   58,   18,   58,

       19,   58,   26,   58,   28,   58,   58,   66,    7,   58
    } ;

static yyconst short int yy_accept[405] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   12,   14,   17,   20,   23,   25,   28,   31,   34,
       37,   40,   43,   46,   49,   52,   55,   59,   62,   65,
       68,   71,   74,   77,   79,   82,   85,   88,   91,   94,
       97,  100,  103,  106,  109,  112,  115,  118,  121,  124,
      127,  130,  134,  137,  140,  143,  145,  147,  149,  152,
      154,  155,  156,  156,  157,  157,  157,  158,  158,  158,
      158,  158,  159,  160,  161,  161,  161,  162,  163,  163,
      164,  165,  165,  166,  167,  167,  167,  168,  169,  169,
      170,  171,  172,  173,  174,  175,  176,  177,  178,  178,

      178,  179,  179,  179,  179,  180,  181,  182,  183,  184,
      185,  186,  187,  188,  190,  191,  192,  193,  194,  195,
      196,  198,  199,  200,  201,  202,  203,  204,  205,  206,
      207,  208,  209,  209,  209,  209,  210,  211,  212,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      214,  214,  214,  214,  214,  215,  215,  216,  216,  217,
      217,  218,  219,  220,  221,  222,  222,  223,  224,  225,
      226,  227,  227,  227,  227,  227,  227,  228,  229,  230,
      231,  232,  233,  234,  235,  236,  237,  238,  239,  240,
      241,  243,  244,  245,  247,  248,  249,  250,  251,  252,

      253,  254,  255,  256,  257,  258,  259,  260,  261,  262,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  264,  264,  264,  264,  264,  264,  264,  265,  266,
      267,  267,  267,  268,  268,  269,  270,  271,  271,  271,
      271,  271,  272,  273,  274,  276,  277,  279,  281,  282,
      283,  284,  285,  287,  289,  290,  291,  293,  294,  296,
      297,  298,  299,  300,  301,  302,  303,  304,  305,  306,
      307,  308,  310,  311,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  313,  314,
      314,  315,  316,  317,  317,  317,  317,  317,  319,  320,

      321,  323,  325,  326,  327,  328,  329,  331,  332,  333,
      334,  335,  337,  338,  339,  340,  341,  342,  343,  345,
      346,  347,  349,  349,  349,  349,  349,  349,  350,  350,
      350,  351,  351,  351,  352,  353,  353,  353,  353,  354,
      355,  356,  357,  358,  360,  362,  364,  365,  366,  368,
      370,  372,  374,  376,  378,  379,  380,  381,  381,  381,
      381,  381,  381,  382,  382,  382,  382,  382,  383,  384,
      385,  387,  388,  389,  391,  392,  393,  393,  393,  393,
      394,  394,  394,  394,  396,  397,  399,  401,  403,  405,
      407,  407,  407,  407,  407,  407,  408,  408,  409,  409,

      409,  409,  411,  411
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   36,
       33,   33,   33,   33,   37,   33,   33,   38,   33,   33,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    3,
        1,    1,    4,    1,    1,    1,    5,    1,    6,    6,
        7,    1,    1,    1,    1,    8,    9,    7,    7,    7,
        7,    7,   10,   10,   10,   10,   11,   11,    1,   11,
        1,    1,   10,    6,    6,    7,    7,    7,    6,   10,
       10,   10,   10,   10,   10,   11,   10,   10,   11,   10,
       11,   11,   11,   10,   11,   10,   10,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[467] =
    {   0,
        0, 1008,   69,   70,   68,   69, 1014, 1016,   74,   77,
      988,   78,   81,   64,   78,  972, 1016,  986,   77, 1016,
       80,   80,   91,  119,  124,  984, 1016,   90,  984,   67,
     1016,  968,  102,  114,  982,   90,   70,   67,  109,  122,
      129,  123,   91,  142,  107,   73,  148,   71,  112,  118,
       83, 1016,  937, 1016,  185, 1002, 1001,  985,    0, 1016,
      193, 1016,  165, 1016,  182,  170, 1016,  954,   71,  952,
      948,  991, 1016, 1016,  183,  188, 1016, 1016,  981,  210,
     1016,  994,  235,  255,  260,  279,  176,  111,  979,  173,
      285,  199,  186,  206, 1016,  970,  969,  953,  153,  208,

     1016,    0,    0,  923,  206,  212,  233,  188,  217,  211,
      238,  245,  247,  257,  254,  267,  270,  271,  273,  275,
      951,  281,  278,  290,  284,  287,  304,  164,  285,  286,
      305,  309,  351,  354,  311,  987,  986, 1016,    0,  346,
        0,    0,    0,  939,  927,  939,  982,  928,  961, 1016,
      352,    0,    0,    0, 1016,  354, 1016,  979, 1016,  357,
      361,  327, 1016,  946,  926,    0,  362,  332, 1016,  944,
      924,    0,    0,    0,    0,  952,  343,  350,  344,  347,
      351,  369,  367,  371,  374,  382,  373,  379,  385,  395,
      936,  372,  388,  935,  396,  390,  383,  397,  398,  405,

      401,  403,  407,  410,  408,  411,  413,  415,  414,  412,
      918,  927,  454,    0,  489,    0,  920,  923,  918,  966,
     1016,  920,  457,    0,  529,    0,  459,  492, 1016, 1016,
      427,  434,  452,  482,  437,  445, 1016,    0,    0,    0,
        0,  446,  435,  465,  927,  490,  926,  925,  443,  476,
      444,  486,  924,  923,  483,  491,  758,  507,  756,  485,
      492,  513,  504,  514,  524,  515,  539,  540,  441,  526,
      543,  755,  528,  544,  739,  516,    0,    0,    0,  736,
      785,  737,  782,  560,    0,    0,    0,  534, 1016,  578,
      582,  748,  728,    0,    0,    0,    0,  736,  550,  554,

      730,  721,  551,  555,  565,  568,  715,  570,  571,  575,
      572,  714,  576,  580,  579,  581,  272,  582,  703,  593,
      586,  666,  643,    0,    0,  656,  700, 1016,  699,  698,
     1016,    0,    0, 1016, 1016,    0,    0,    0,  660,  595,
      594,  597,  599,  659,  658,  657,  600,  601,  656,  655,
      653,  652,  650,  648,  604,  606,  611,  637,    0,  639,
      678,  675, 1016,    0,  642,    0,    0,  615,  617,  616,
      636,  618,  622,  635,  623,  626,  624,    0,  585, 1016,
        0,    0,    0,  547,  627,  450,  345,  222,  166,  163,
      667,    0,    0,    0,    0,  628,  683, 1016,    0,    0,

        0,   82, 1016,  707,  718,  729,  740,  746,  757,  768,
      778,  788,  799,  806,  808,  810,  812,  814,  816,  823,
      829,  831,  833,  835,  837,  839,  841,  843,  845,  847,
      849,  851,  853,  855,  857,  859,  861,  863,  870,  881,
      887,  889,  891,  893,  895,  897,  899,  901,  908,  914,
      916,  918,  920,  922,  924,  931,  937,  939,  941,  943,
      945,  947,  949,  951,  953,  955
    } ;

static yyconst short int yy_def[467] =
    {   0,
      403,    1,  404,  404,  405,  405,  403,  403,  403,  403,
      403,  406,  403,  403,  403,  407,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  408,  408,  403,  403,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  403,  403,  403,  403,  409,  409,  403,  410,  403,
      403,  403,  406,  403,  411,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  407,  412,  403,  403,  403,  403,
      403,  413,  403,  403,  403,  403,  403,  403,  414,  403,
      403,  403,  403,  403,  403,  403,  403,  408,  403,  406,

      403,  415,  416,  403,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  403,  403,  403,  409,  409,  403,  410,  406,
      417,  418,  419,  403,  403,  403,  420,  403,  403,  403,
      407,  421,  422,  423,  403,  403,  403,  413,  403,  403,
      403,  403,  403,  403,  403,  424,  414,  403,  403,  403,
      403,  425,  426,  427,  428,  403,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      403,  403,  406,  429,  406,  430,  403,  403,  403,  420,
      403,  403,  407,  431,  407,  432,  403,  403,  403,  403,
      424,  424,  403,  403,  403,  403,  403,  433,  434,  435,
      436,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  403,  406,  437,  215,  438,  403,
      439,  403,  440,  407,  441,  225,  442,  403,  403,  403,
      403,  403,  403,  443,  444,  445,  446,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  403,  447,  448,  403,  439,  403,  449,  440,
      403,  450,  451,  403,  403,  452,  453,  454,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  403,  455,  406,
      456,  449,  403,  457,  407,  458,  459,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  403,  460,  456,  403,
      461,  462,  463,  408,  408,  408,  408,  408,  408,  408,
      403,  464,  465,  466,  446,  408,  403,  403,  448,  451,

      453,  408,    0,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403
    } ;

static yyconst short int yy_nxt[1088] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   26,   27,   28,   29,   30,   31,   32,   32,   32,
       32,   32,   32,   32,   33,   32,   32,   32,   17,   34,
       17,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       32,   44,   32,   45,   32,   32,   32,   32,   46,   47,
       48,   49,   50,   51,   32,   32,   32,   52,   53,   17,
       54,   57,   57,   60,   60,   61,   61,   61,   61,   61,
       61,   58,   58,   64,   66,   72,   62,   67,   73,   74,
       77,   62,   97,   60,   60,   77,   79,   95,   80,   80,

       80,   73,   73,   81,   73,   78,   99,  100,   82,   99,
       99,   74,   99,   96,   62,   73,  101,   65,  105,  106,
      124,   99,   99,  107,  145,  109,  146,   68,   69,   99,
       99,  108,   70,  132,   71,   83,  129,   84,   84,   85,
       83,   99,   91,   91,   91,  164,   99,  120,   99,   86,
      102,   99,  110,   87,   86,   88,   89,   99,   92,  111,
       93,   99,   99,  123,  165,  112,   86,  130,   99,  113,
       64,   86,   90,   66,  131,  103,  118,   94,  114,  119,
       88,   99,  115,   89,  116,   93,  133,   99,  134,  172,
      121,   67,  150,  117,   61,   61,   61,  122,  125,  126,

      140,  140,   99,   99,   65,   99,  151,  151,  127,  163,
      162,  128,  163,   64,  173,  204,   68,   69,  141,  142,
      170,   70,   76,   71,  152,  153,  162,   99,   80,   80,
       80,   68,   69,  168,  163,  169,  135,  163,   71,  171,
      156,  157,  169,  143,  157,   99,  142,   65,  180,  154,
       99,   99,  153,   80,   80,   80,   99,  156,  157,  168,
      169,   99,  177,  157,  181,  156,  157,  169,  178,  157,
      182,   83,   99,   84,   84,   85,   83,   99,   85,   85,
       85,  183,  156,  157,   99,   86,   99,  179,  157,   87,
       86,   88,  160,   99,  160,  185,   99,  161,  161,  161,

      184,   83,   86,   91,   91,   91,   99,   86,   90,   99,
       99,   99,   99,  187,   99,   86,   88,   99,  186,   92,
       99,   93,  354,   99,   99,   99,   99,  190,  188,   99,
      189,  191,   86,  195,  193,  192,  200,  206,   94,  196,
      199,  194,  205,   99,   99,  207,   93,  202,   99,  197,
      198,   64,  133,  201,  133,  133,  208,  134,  209,  147,
      210,  150,  203,  163,  213,  213,  212,  227,  169,  227,
      223,  223,  228,  228,  228,  161,  161,  161,  232,  161,
      161,  161,   99,   99,   99,   65,   99,  244,  163,   99,
       99,   76,  229,  169,  246,  229,  233,  234,  235,  242,

       68,   69,  211,  245,  243,  135,   99,   71,   99,  229,
       99,   99,   99,   99,  229,  236,  247,  251,   99,  234,
      253,   99,   99,  235,   99,  248,  252,   99,  257,   99,
      249,  250,  255,  254,   99,   99,   99,   99,  256,  258,
       99,  260,   99,  261,   99,  259,   99,   99,  265,   99,
       99,   99,   99,   99,   99,  269,  263,  273,  262,   64,
      264,  272,  234,  266,  271,  274,  150,  270,  267,  234,
      268,  292,  276,  276,   99,  284,  284,  228,  228,  228,
       99,  289,   99,   99,  234,   99,  288,  318,  289,   99,
      293,  234,  299,   65,   64,  290,   76,  290,  288,  298,

      291,  291,  291,  302,   99,  304,  289,  278,  278,  278,
      228,  228,  228,  289,  300,   99,  278,  278,  278,  278,
      278,   64,   99,  157,   99,   99,  157,  303,   65,   99,
       99,   99,  278,  278,  278,  278,  278,  278,  150,  305,
      157,  306,  301,   99,  309,  157,   99,  286,  286,  286,
      310,  307,   99,   99,   99,   65,  286,  286,  286,  286,
      286,  313,  308,   99,  312,   99,  315,   99,   76,  150,
      289,  311,  286,  286,  286,  286,  286,  286,   99,   99,
      314,  319,   99,   99,  316,  317,   99,  380,  321,   99,
       99,  322,  320,   99,   99,  289,  291,  291,  291,   76,

      291,  291,  291,  340,   99,  341,  342,   99,  343,   99,
       99,   99,  344,  334,   99,   99,  334,  346,   99,   99,
       99,   99,  350,  345,  352,   99,  348,  349,  351,  355,
      334,  347,   99,   99,   99,  334,   99,  357,   99,   99,
       99,  353,  368,   99,   64,   99,  373,  372,  356,  369,
       99,  150,  374,  375,   99,   99,   99,   99,  370,  371,
      385,   99,   99,  386,  376,   99,   99,   99,  397,  389,
      397,  391,  398,  390,   99,   99,  387,  363,   65,  384,
      380,   76,  388,  377,  397,  396,  397,   99,  398,   99,
      398,   99,   99,  402,   99,   99,   99,   99,   99,   99,

      331,  363,  328,  361,  358,   99,  398,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       75,   75,   99,   75,   75,   75,   75,   75,   75,   75,
       75,   98,   98,   99,   99,   98,   98,  136,  136,  136,
       99,  136,  136,  136,  136,  136,  136,  136,  139,   99,
      139,  139,  139,  139,  139,   99,  139,  139,  139,   63,
       63,  335,  335,   63,  331,  329,   63,  328,   63,   75,
       75,  326,  323,   75,   99,   99,   75,   99,   75,  158,

      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      167,  167,  167,  174,  174,  175,  175,  214,  214,  215,
      215,  216,  216,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  224,  224,  225,  225,  226,  226,
      231,  231,  238,  238,  239,  239,  240,  240,  241,  241,
      277,  277,  279,  279,  285,  285,  287,  287,  294,  294,
      295,  295,  296,  296,  297,  297,  324,  324,  325,  325,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  332,  332,  333,  333,  336,  336,  337,  337,

      338,  338,  339,  339,  359,  359,  360,  360,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  364,
      364,  365,  365,  366,  366,   98,   98,  367,  367,  378,
      378,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  381,  381,  382,  382,  383,  383,  392,  392,
      393,  393,  394,  394,  395,  395,  399,  399,  400,  400,
      401,  401,   99,   99,   99,   99,   99,  283,  221,  282,
      281,  280,  275,  212,   99,   99,   73,  237,  237,  230,
      230,  159,   74,  222,  221,  219,  218,  217,  137,  137,
       99,  176,   99,   73,   73,  166,  159,  155,  149,  148,

      147,  144,  138,  137,  137,   62,  104,   99,   62,   74,
       73,   76,   62,  403,   55,    7,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403
    } ;

static yyconst short int yy_chk[1088] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    9,    9,    9,   10,   10,
       10,    3,    4,   12,   13,   14,   15,   13,   14,   14,
       19,   30,   30,    5,    6,   21,   22,   28,   22,   22,

       22,   19,   15,   23,   21,   21,   38,   33,   23,   37,
       48,   28,   46,   28,   28,   23,   34,   12,   36,   36,
       46,  402,   51,   36,   69,   38,   69,   13,   13,   36,
       43,   37,   13,   51,   13,   24,   48,   24,   24,   24,
       25,   33,   25,   25,   25,   88,   45,   43,   39,   24,
       34,   49,   39,   24,   25,   24,   24,   50,   25,   39,
       25,   40,   42,   45,   88,   39,   24,   49,   41,   40,
       63,   25,   24,   66,   50,   34,   42,   25,   40,   42,
       24,   44,   41,   24,   41,   25,   55,   47,   55,   99,
       44,   55,   75,   41,   61,   61,   61,   44,   47,   47,

       65,   65,  390,  128,   63,  389,   76,   76,   47,   90,
       87,   47,   87,  100,   99,  128,   66,   66,   65,   65,
       93,   66,   75,   66,   76,   76,   90,  108,   80,   80,
       80,   55,   55,   92,   90,   92,   55,   87,   55,   93,
       80,   80,   94,   65,   80,  105,   65,  100,  108,   76,
      110,  106,   76,   83,   83,   83,  109,   80,   80,   94,
       92,  388,  105,   80,  109,   83,   83,   94,  106,   83,
      110,   84,  107,   84,   84,   84,   85,  111,   85,   85,
       85,  111,   83,   83,  112,   84,  113,  107,   83,   84,
       85,   84,   86,  115,   86,  113,  114,   86,   86,   86,

      112,   91,   84,   91,   91,   91,  116,   85,   84,  117,
      118,  317,  119,  115,  120,   91,   84,  123,  114,   91,
      122,   91,  317,  125,  129,  130,  126,  118,  116,  124,
      117,  119,   91,  123,  122,  120,  126,  130,   91,  124,
      125,  122,  129,  127,  131,  130,   91,  127,  132,  124,
      124,  140,  133,  126,  133,  134,  131,  134,  131,  135,
      132,  151,  127,  162,  140,  140,  135,  156,  168,  156,
      151,  151,  156,  156,  156,  160,  160,  160,  167,  161,
      161,  161,  177,  179,  387,  140,  180,  179,  162,  178,
      181,  151,  161,  168,  181,  161,  167,  167,  167,  177,

      134,  134,  133,  180,  178,  134,  183,  134,  182,  161,
      184,  192,  187,  185,  161,  167,  182,  185,  188,  167,
      187,  186,  197,  167,  189,  183,  186,  193,  192,  196,
      184,  184,  189,  188,  190,  195,  198,  199,  190,  193,
      201,  196,  202,  197,  200,  195,  203,  205,  201,  204,
      206,  210,  207,  209,  208,  205,  199,  209,  198,  213,
      200,  208,  231,  202,  207,  210,  223,  206,  203,  232,
      204,  235,  213,  213,  243,  223,  223,  227,  227,  227,
      269,  236,  249,  251,  231,  242,  233,  269,  233,  386,
      235,  232,  243,  213,  215,  234,  223,  234,  236,  242,

      234,  234,  234,  249,  244,  251,  236,  215,  215,  215,
      228,  228,  228,  233,  244,  250,  215,  215,  215,  215,
      215,  276,  255,  228,  260,  252,  228,  250,  215,  246,
      256,  261,  215,  215,  215,  215,  215,  215,  225,  252,
      228,  255,  246,  263,  260,  228,  258,  225,  225,  225,
      261,  256,  262,  264,  266,  276,  225,  225,  225,  225,
      225,  264,  258,  265,  263,  270,  266,  273,  225,  284,
      288,  262,  225,  225,  225,  225,  225,  225,  267,  268,
      265,  270,  271,  274,  267,  268,  384,  379,  273,  299,
      303,  274,  271,  300,  304,  288,  290,  290,  290,  284,

      291,  291,  291,  299,  305,  300,  303,  306,  304,  308,
      309,  311,  305,  291,  310,  313,  291,  308,  315,  314,
      316,  318,  313,  306,  315,  321,  310,  311,  314,  318,
      291,  309,  320,  341,  340,  291,  342,  321,  343,  347,
      348,  316,  340,  355,  360,  356,  348,  347,  320,  341,
      357,  365,  355,  356,  368,  370,  369,  372,  342,  343,
      369,  373,  375,  370,  357,  376,  385,  396,  391,  375,
      391,  377,  391,  376,  374,  371,  372,  362,  360,  368,
      361,  365,  373,  358,  397,  385,  397,  354,  397,  353,
      391,  352,  351,  396,  350,  349,  346,  345,  344,  339,

      330,  329,  327,  326,  323,  322,  397,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      407,  407,  319,  407,  407,  407,  407,  407,  407,  407,
      407,  408,  408,  312,  307,  408,  408,  409,  409,  409,
      302,  409,  409,  409,  409,  409,  409,  409,  410,  301,
      410,  410,  410,  410,  410,  298,  410,  410,  410,  411,
      411,  293,  292,  411,  283,  282,  411,  281,  411,  412,
      412,  280,  275,  412,  272,  259,  412,  257,  412,  413,

      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      414,  414,  414,  415,  415,  416,  416,  417,  417,  418,
      418,  419,  419,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  421,  421,  422,  422,  423,  423,
      424,  424,  425,  425,  426,  426,  427,  427,  428,  428,
      429,  429,  430,  430,  431,  431,  432,  432,  433,  433,
      434,  434,  435,  435,  436,  436,  437,  437,  438,  438,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  440,  440,  440,  440,  440,  440,  440,  440,  440,
      440,  440,  441,  441,  442,  442,  443,  443,  444,  444,

      445,  445,  446,  446,  447,  447,  448,  448,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  450,
      450,  451,  451,  452,  452,  453,  453,  454,  454,  455,
      455,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  457,  457,  458,  458,  459,  459,  460,  460,
      461,  461,  462,  462,  463,  463,  464,  464,  465,  465,
      466,  466,  254,  253,  248,  247,  245,  222,  220,  219,
      218,  217,  212,  211,  194,  191,  176,  171,  170,  165,
      164,  158,  149,  148,  147,  146,  145,  144,  137,  136,
      121,  104,   98,   97,   96,   89,   82,   79,   72,   71,

       70,   68,   58,   57,   56,   53,   35,   32,   29,   26,
       18,   16,   11,    7,    2,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fb2-5.l"
#define INITIAL 0
/* fb2-5 C cross-ref */
#define COMMENT 1

#define IFILE 2

/* some complex named patterns */
/* Universal Character Name */
/* float exponent */
/* integer length */
/* the symbol table */
#line 17 "fb2-5.l"
    #include <string.h>

    struct symbol { /* a variable name */
        struct ref *reflist;
        char *name;
    };

    struct ref {
        struct ref *next;
        char *filename;
        int flags; /* 01 - definition */
        int lineno;
    };
        
    /* simple symtab of fixed size */
    #define NHASH 9997
    struct symbol symtab[NHASH];
    
    struct symbol *lookup(char*);
    void addref(int, char*, char*, int);
    
    char *curfilename;          /* name of current input file */
    
    /* include file stack */
    struct bufstack {
        struct bufstack *prev;  /* previous entry */
        YY_BUFFER_STATE bs;     /* saved buffer */
        int lineno;             /* saved line number in this file */
        char *filename;         /* name of this file */
        FILE *f;                /* current file */
    } *curbs;

    int newfile(char *fn);
    int popfile(void);
    int defining;               /* names are probably definitions */

#line 856 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 55 "fb2-5.l"

    /* comments */
#line 1013 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 404 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1016 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 57 "fb2-5.l"
{ BEGIN(COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "fb2-5.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "fb2-5.l"

	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 60 "fb2-5.l"
{ printf("%s:%d: Unterminated comment\n", curfilename, yylineno); return 0; }
	YY_BREAK
/* C++ comment, a common extension */
case 4:
YY_RULE_SETUP
#line 62 "fb2-5.l"

	YY_BREAK
/* declaration keywords */
case 5:
#line 65 "fb2-5.l"
case 6:
#line 66 "fb2-5.l"
case 7:
#line 67 "fb2-5.l"
case 8:
#line 68 "fb2-5.l"
case 9:
#line 69 "fb2-5.l"
case 10:
#line 70 "fb2-5.l"
case 11:
#line 71 "fb2-5.l"
case 12:
#line 72 "fb2-5.l"
case 13:
#line 73 "fb2-5.l"
case 14:
#line 74 "fb2-5.l"
case 15:
#line 75 "fb2-5.l"
case 16:
#line 76 "fb2-5.l"
case 17:
#line 77 "fb2-5.l"
case 18:
#line 78 "fb2-5.l"
case 19:
#line 79 "fb2-5.l"
case 20:
#line 80 "fb2-5.l"
case 21:
#line 81 "fb2-5.l"
case 22:
#line 82 "fb2-5.l"
case 23:
#line 83 "fb2-5.l"
case 24:
#line 84 "fb2-5.l"
case 25:
#line 85 "fb2-5.l"
case 26:
#line 86 "fb2-5.l"
case 27:
#line 87 "fb2-5.l"
case 28:
YY_RULE_SETUP
#line 87 "fb2-5.l"
{ defining = 1; }
	YY_BREAK
/* keywords */
case 29:
YY_RULE_SETUP
#line 90 "fb2-5.l"

	YY_BREAK
case 30:
YY_RULE_SETUP
#line 91 "fb2-5.l"

	YY_BREAK
case 31:
YY_RULE_SETUP
#line 92 "fb2-5.l"

	YY_BREAK
case 32:
YY_RULE_SETUP
#line 93 "fb2-5.l"

	YY_BREAK
case 33:
YY_RULE_SETUP
#line 94 "fb2-5.l"

	YY_BREAK
case 34:
YY_RULE_SETUP
#line 95 "fb2-5.l"

	YY_BREAK
case 35:
YY_RULE_SETUP
#line 96 "fb2-5.l"

	YY_BREAK
case 36:
YY_RULE_SETUP
#line 97 "fb2-5.l"

	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "fb2-5.l"

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 "fb2-5.l"

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 100 "fb2-5.l"

	YY_BREAK
case 40:
YY_RULE_SETUP
#line 101 "fb2-5.l"

	YY_BREAK
case 41:
YY_RULE_SETUP
#line 102 "fb2-5.l"

	YY_BREAK
/* constants */
/* integers */
case 42:
YY_RULE_SETUP
#line 106 "fb2-5.l"

	YY_BREAK
case 43:
YY_RULE_SETUP
#line 107 "fb2-5.l"

	YY_BREAK
case 44:
YY_RULE_SETUP
#line 108 "fb2-5.l"

	YY_BREAK
/* decimal float */
case 45:
YY_RULE_SETUP
#line 111 "fb2-5.l"

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 112 "fb2-5.l"

	YY_BREAK
/* hex float */
case 47:
YY_RULE_SETUP
#line 115 "fb2-5.l"

	YY_BREAK
/* char const */
case 48:
YY_RULE_SETUP
#line 117 "fb2-5.l"

	YY_BREAK
/* string literal */
case 49:
YY_RULE_SETUP
#line 119 "fb2-5.l"

	YY_BREAK
/* punctuators */
case 50:
YY_RULE_SETUP
#line 122 "fb2-5.l"
{ defining = 0; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 123 "fb2-5.l"

	YY_BREAK
case 52:
YY_RULE_SETUP
#line 124 "fb2-5.l"

	YY_BREAK
case 53:
YY_RULE_SETUP
#line 125 "fb2-5.l"

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 126 "fb2-5.l"

	YY_BREAK
case 55:
YY_RULE_SETUP
#line 127 "fb2-5.l"

	YY_BREAK
case 56:
YY_RULE_SETUP
#line 128 "fb2-5.l"

	YY_BREAK
case 57:
YY_RULE_SETUP
#line 129 "fb2-5.l"

	YY_BREAK
/* identifier */
case 58:
YY_RULE_SETUP
#line 132 "fb2-5.l"
{ addref(yylineno, curfilename, yytext, defining); }
	YY_BREAK
/* whitespace */
case 59:
YY_RULE_SETUP
#line 135 "fb2-5.l"

	YY_BREAK
/* continued line */
case 60:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 138 "fb2-5.l"

	YY_BREAK
/* some preprocessor stuff */
case 61:
YY_RULE_SETUP
#line 141 "fb2-5.l"

	YY_BREAK
case 62:
YY_RULE_SETUP
#line 142 "fb2-5.l"

	YY_BREAK
case 63:
YY_RULE_SETUP
#line 143 "fb2-5.l"

	YY_BREAK
case 64:
YY_RULE_SETUP
#line 144 "fb2-5.l"

	YY_BREAK
case 65:
YY_RULE_SETUP
#line 145 "fb2-5.l"

	YY_BREAK
/* recognize an include */
case 66:
YY_RULE_SETUP
#line 148 "fb2-5.l"
{ BEGIN IFILE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 149 "fb2-5.l"
{
                                            {   int c;
                                                while((c = input()) && c != '\n') ;
                                            }
                                            newfile(strdup(yytext));
                                            BEGIN INITIAL;
                                        }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 156 "fb2-5.l"
{ fprintf(stderr, "%s:%d bad include line\n", curfilename, yylineno);
                                            BEGIN INITIAL;
                                        }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IFILE):
#line 159 "fb2-5.l"
{ if(!popfile()) yyterminate(); }
	YY_BREAK
/* invalid character */
case 69:
YY_RULE_SETUP
#line 162 "fb2-5.l"
{ printf("%s:%d: Mystery character '%s'\n", curfilename, yylineno, yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 164 "fb2-5.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1422 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 404 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 404 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 403);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 164 "fb2-5.l"


int
main(argc, argv)
int argc;
char **argv;
{
    int i;
    if(argc < 2) {
        fprintf(stderr, "need filename\n");
        return 1;
    }
    for(i = 1; i < argc; i++) {
        if(newfile(argv[i]))
        yylex();
    }
    printrefs();
    return 0;
}

/* hash a symbol */
static unsigned
symhash(char *sym)
{
    unsigned int hash = 0;
    unsigned c;
    while(c = *sym++) hash = hash*9 ^ c;
    return hash;
}

struct symbol *
lookup(char* sym)
{
    struct symbol *sp = &symtab[symhash(sym)%NHASH];
    int scount = NHASH; /* how many have we looked at */
    while(--scount >= 0) {
        if(sp->name && !strcmp(sp->name, sym)) return sp;
        if(!sp->name) { /* new entry */
            sp->name = strdup(sym);
            sp->reflist = 0;
            return sp;
        }
        if(++sp >= symtab+NHASH) sp = symtab; /* try the next entry */
    }
    fputs("symbol table overflow\n", stderr);
    abort(); /* tried them all, table is full */
}

void
addref(int lineno, char *filename, char *word, int flags)
{
    struct ref *r;
    struct symbol *sp = lookup(word);
    /* don't do dups of same line and file */
    if(sp->reflist &&
    sp->reflist->lineno == lineno &&
    sp->reflist->filename == filename) return;
    r = malloc(sizeof(struct ref));
    if(!r) {fputs("out of space\n", stderr); abort(); }
    r->next = sp->reflist;
    r->filename = filename;
    r->lineno = lineno;
    r->flags = flags;
    sp->reflist = r;
}

/* print the references
* sort the table alphabetically
* then flip each entry's reflist to get it into forward order
* and print it out
*/
/* aux function for sorting */
static int
symcompare(const void *xa, const void *xb)
{
    const struct symbol *a = xa;
    const struct symbol *b = xb;
    if(!a->name) {
        if(!b->name) return 0; /* both empty */
        return 1; /* put empties at the end */
    }
    if(!b->name) return -1;
    return strcmp(a->name, b->name);
}

void
printrefs()
{
    struct symbol *sp;
    qsort(symtab, NHASH, sizeof(struct symbol), symcompare);    /* sort the symbol table */
    for(sp = symtab; sp->name && sp < symtab+NHASH; sp++) {
        char *prevfn = NULL;                                    /* last printed filename, to skip dups */
        /* reverse the list of references */
        struct ref *rp = sp->reflist;
        struct ref *rpp = 0;                                    /* previous ref */
        struct ref *rpn;                                        /* next ref */
        do {
            rpn = rp->next;
            rp->next = rpp;
            rpp = rp;
            rp = rpn;
        } while(rp);
        /* now print the word and its references */
        printf("%10s", sp->name);
        for(rp = rpp; rp; rp = rp->next) {
            if(rp->filename == prevfn) {
                printf(" %d", rp->lineno);
            } else {
                printf(" %s:%d", rp->filename, rp->lineno);
                prevfn = rp->filename;
            }
            if(rp->flags & 01) printf("*");
        }
        printf("\n");
    }
}

int newfile(char *fn)
{
    FILE *f = fopen(fn, "r");
    struct bufstack *bs = malloc(sizeof(struct bufstack));
    /* die if no file or no room */
    if(!f) { perror(fn); return 0; }
    if(!bs) { perror("malloc"); exit(1); }
    /* remember state */
    if(curbs)curbs->lineno = yylineno;
    bs->prev = curbs;
    /* set up current entry */
    bs->bs = yy_create_buffer(f, YY_BUF_SIZE);
    bs->f = f;
    bs->filename = fn;
    yy_switch_to_buffer(bs->bs);
    curbs = bs;
    yylineno = 1;
    curfilename = fn;
    return 1;
}

int
popfile(void)
{
    struct bufstack *bs = curbs;
    struct bufstack *prevbs;
    if(!bs) return 0;
    /* get rid of current entry
    fclose(bs->f);
    yy_delete_buffer(bs->bs);
    /* switch back to previous */
    prevbs = bs->prev;
    free(bs);
    if(!prevbs) return 0;
    yy_switch_to_buffer(prevbs->bs);
    curbs = prevbs;
    yylineno = curbs->lineno;
    curfilename = curbs->filename;
    return 1;
}